---
name: CrateKeys
main: CrateKeys\Main
version: 1.0.5
api: [1.13.0]
load: POSTWORLD
author: CDFalcon
authors: [CDFalcon] ##Editor LordJoshie of PCPE (PureCraftPE)##
website: https://github.com/CDFalcon/Pocketmine-MP-Plugins <--- whoever this dingdong is... lol
commands:
